name: ci/cd

on: [push]
jobs:
  SECURITY:
    env:
      SYNK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    runs-on: ubuntu-20.04
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: scan iac
      shell: bash
      run: make scan_iac
    - uses: actions/upload-artifact@v3
      with:
        name: iac_report
        path: iac/vuln.json
  CI:
    needs: [ SECURITY ]
    env:
      PAT: ${{ secrets.PAT }}
      CR_HOST: ${{ vars.CR_HOST }}
    runs-on: ubuntu-20.04
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: lint docker image
      shell: bash
      run: make lint
    - name: login to ghcr
      shell: bash
      run: make login
    - name: build
      shell: bash
      run: make build_image
    - name: deploy
      shell: bash
      run: make deploy_image
  CD:
    needs: [ CI ]
    environment: 
      name: apply
    env:
      PAT: ${{ secrets.PAT }}
      CR_HOST: ${{ vars.CR_HOST }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    runs-on: ubuntu-20.04
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: generate doc
      shell: bash
      run: make doc
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: updating doc
    - name: init terraform
      shell: bash
      run: make init
    - name: plan terraform
      shell: bash
      run: make plan
    - name: apply terraform
      shell: bash
      run: make apply