name: ci/cd

on: [push]
jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: login to ghcr
      shell: bash
      run: make login