name: ci/cd

on: [push]
jobs:
  CI:
    env:
      PAT: ${{ secrets.PAT }}
      CR_HOST: ${{ vars.CR_HOST }}
    runs-on: ubuntu-20.04
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: login to ghcr
      shell: bash
      run: make login
    - name: build
      shell: bash
      run: make build_image
    - name: deploy
      shell: bash
      run: make deploy_image